// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://makjqyvoaniafsstmlfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ha2pxeXZvYW5pYWZzc3RtbGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDgwMzUsImV4cCI6MjA3MzQyNDAzNX0.Gs5DWX1-m2zNnVC4OHxUZiaBh1Mj9-jjow_YhrRR2uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});